# Generated by Django 5.2.6 on 2025-09-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPP', '0002_task_user_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_login',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(),
        ),
    ]
