# Generated by Django 5.2.5 on 2025-10-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPP', '0006_alter_task_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
