# Generated by Django 5.2.5 on 2025-11-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPP', '0008_remove_task_end_time_remove_task_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclictask',
            name='occurrences_count',
            field=models.IntegerField(default=12),
        ),
    ]
