# Generated by Django 5.2.5 on 2025-11-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPP', '0009_cyclictask_occurrences_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_points_earned',
            field=models.IntegerField(default=0),
        ),
    ]
