# Generated by Django 5.2.5 on 2025-11-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPP', '0010_userprofile_total_points_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points_spent',
            field=models.IntegerField(default=0),
        ),
    ]
