# Generated by Django 5.2.5 on 2025-11-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPP', '0011_userprofile_points_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('school', 'School/Studies'), ('private', 'Private')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
